---
# handlers file for ara

- name: Restart ara
  ansible.builtin.service:
    name: ara
    state: restarted
  become: true
  become_user: root
  when:
    - not ansible_check_mode | bool

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  become_user: root
  changed_when: false
  failed_when: false
  notify:
    - Restart ara
